- name: Create source directory
  file:
    path: "{{ SOURCE_DIR }}"
    state: directory

- name: Download and Extract dahdi linux current package
  unarchive:
    src: "{{ DAHDI_CURRENT_PACKAGE }}"
    dest: "{{ SOURCE_DIR }}"
    remote_src: yes
  notify: Install Dahdi current Linux
  register: downloaddahdi

- name: Get dahdi package directory name
  command: find "{{ SOURCE_DIR }}" -type d -name "dahdi-linux-complete-*"
  register: dahdi_directory
  changed_when: False
  failed_when: False
  #when: downloaddahdi.changed

- meta: flush_handlers

- debug:
    msg: "Dahdi directory name is {{ dahdi_directory.stdout }}"