- name: Download and Extract Libpri 1.6 Package
  unarchive:
    src: "{{ LIBPRI_PACKAGE }}"
    dest: "{{ SOURCE_DIR }}"
    remote_src: yes
    list_files: yes
  register: libpri_archive_contents

- debug:
    msg: "Libpri Package directory path is: {{ SOURCE_DIR }}{{ libpri_archive_contents.files[0] }}"

- name: Install Libpri 1.6 Package
  command: "{{ item }}"
  with_items:
    - make all
    - make install
  args:
    chdir: "{{ SOURCE_DIR }}{{ libpri_archive_contents.files[0] }}"
  notify: restart asterisk server
  when: libpri_archive_contents.files[0] is search ('libpri')

- meta: flush_handlers