- name: Install epel repo
  dnf:
    name: epel-release
    state: present

- name: install mysql-connector repository
  dnf:
    name: http://repo.mysql.com/mysql80-community-release-el8.rpm
    state: present

- name: Update system
  dnf:
    name: "*"
    state: latest
  register: allupdate

- name: Reboot machine after update and wait reconnect
  reboot:
    reboot_timeout: 3600
  when: allupdate is changed

- name: Install required packages
  dnf:
    name: "{{ packages_required }}"
    state: present