---
# handlers file for AsteriskInstall
- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
    enabled: yes

- name: restart asterisk server
  service:
    name: asterisk
    state: restarted
    enabled: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: yes

- name: Apply Selinux File context to Asterisk File
  command: restorecon -irv "{{ item }}"
  with_items:
    - /etc/asterisk
    - /usr/lib64/asterisk/modules
    - /var/lib/asterisk
    - /var/spool/asterisk
    - /var/run/asterisk
    - /var/log/asterisk